{% set data = load_setup_py_data() %}
{% set version = data.get('version') or 'placehold' %}
{% set release = '.'.join(version.split('.')[:2]) %}

package:
  name: q2-dada2
  version: {{ version }}

source:
  path: ../..

build:
  script: make install

requirements:
  host:
    - python {{ python }}
    - setuptools

  run:
    - python {{ python }}
    - biom-format >=2.1.5,<2.2a0
    - bioconductor-dada2 1.18.0
    # the following pin is due to recent issues with versions of r-matrix
    # past 1.3-2:
    # https://github.com/benjjneb/dada2/issues/212#issuecomment-836757295
    - r-matrix 1.3-2
    # openjdk is not a real dependency, but, r-base has a post-link and post-
    # activation hook that calls R CMD javareconf, which pokes around for any
    # installations of java. On modern versions of macOS, a binary called
    # `java` is included, but it only launches a GUI installation alert,
    # indicating to the user that there is no "true" installation of java
    # present. By including openjdk on osx hosts, this pop-up is prevented at
    # installation and activation time of the environment.
    - openjdk # [osx]
    - qiime2 {{ qiime2 }}
    - q2-types {{ q2_types }}

test:
  requires:
    - pytest

  imports:
    - q2_dada2
    - qiime2.plugins.dada2

about:
  home: https://qiime2.org
  license: BSD-3-Clause
  license_family: BSD
